/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.LeKhanh;

import Controller.BillDAOImpl;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import Models.*;
import javax.swing.JFrame;

/**
 *
 * @author LeKhanh
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    int[] listUnit = new int[6];
    DecimalFormat formatter = new DecimalFormat("#.###");
    Connection con;
    int billId;

    public Payment(Object[] o, Connection con) {
        initComponents();
        this.con = con;
        jname.setText(o[3].toString() + " " + o[2].toString() + " " + o[1].toString());
        jadd.setText(o[4].toString() + ", " + o[5].toString());
        jcusid.setText(o[0].toString());
        jmeasid.setText(o[6].toString());
        jphone.setText(o[7].toString());
        this.billId = (int) o[12];
        jBillId.setText(billId + "");
        int csc1 = (int) o[10];
        int csm = (int) o[11];
        this.csc1.setText(csc1 + "");
        this.csm.setText(csm + "");
        int tongDN = csm - csc1;
        this.tong.setText(tongDN + "");
        int[] dntt = new int[6];
        dntt = tinhDN(tongDN);
        tt1.setText(dntt[0] + "");
        tt2.setText(dntt[1] + "");
        tt3.setText(dntt[2] + "");
        tt4.setText(dntt[3] + "");
        tt5.setText(dntt[4] + "");
        tt6.setText(dntt[5] + "");
        double thanhtien1 = Double.parseDouble(formatter.format(dntt[0] * Double.parseDouble(dg1.getText())));
        double thanhtien2 = Double.parseDouble(formatter.format(dntt[1] * Double.parseDouble(dg2.getText())));
        double thanhtien3 = Double.parseDouble(formatter.format(dntt[2] * Double.parseDouble(dg3.getText())));
        double thanhtien4 = Double.parseDouble(formatter.format(dntt[3] * Double.parseDouble(dg4.getText())));
        double thanhtien5 = Double.parseDouble(formatter.format(dntt[4] * Double.parseDouble(dg5.getText())));
        double thanhtien6 = Double.parseDouble(formatter.format(dntt[5] * Double.parseDouble(dg6.getText())));
        tien1.setText(thanhtien1 + "");
        tien2.setText(thanhtien2 + "");
        tien3.setText(thanhtien3 + "");
        tien4.setText(thanhtien4 + "");
        tien5.setText(thanhtien5 + "");
        tien6.setText(thanhtien6 + "");
        tongtt.setText(tongDN + "");

        double tongThanhTien = Double.parseDouble(formatter.format(thanhtien1
                + thanhtien2
                + thanhtien3
                + thanhtien4
                + thanhtien5
                + thanhtien6));
        
        tongthanhtien.setText(tongThanhTien + "");
        thue1.setText(formatter.format(tongThanhTien * 0.1));
        tongcong.setText(normalize(formatter.format(tongThanhTien + tongThanhTien * 0.1)));
        bangchu.setText(toWord(tongcong.getText().split("\\.")));
        tien1.setText(normalize(tien1.getText()));
        tien2.setText(normalize(tien2.getText()));
        tien3.setText(normalize(tien3.getText()));
        tien4.setText(normalize(tien4.getText()));
        tien5.setText(normalize(tien5.getText()));
        tien6.setText(normalize(tien6.getText()));
        tongthanhtien.setText(normalize(tongthanhtien.getText()));
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmeasid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBillId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jadd = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jphone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jcusid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dg1 = new javax.swing.JLabel();
        tien4 = new javax.swing.JLabel();
        csm = new javax.swing.JLabel();
        tt1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tong = new javax.swing.JLabel();
        tt3 = new javax.swing.JLabel();
        tt2 = new javax.swing.JLabel();
        tt5 = new javax.swing.JLabel();
        tongtt = new javax.swing.JLabel();
        tt4 = new javax.swing.JLabel();
        dg2 = new javax.swing.JLabel();
        dg3 = new javax.swing.JLabel();
        dg4 = new javax.swing.JLabel();
        dg5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        tien2 = new javax.swing.JLabel();
        tien3 = new javax.swing.JLabel();
        tien5 = new javax.swing.JLabel();
        tongthanhtien = new javax.swing.JLabel();
        tien1 = new javax.swing.JLabel();
        csc1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tt6 = new javax.swing.JLabel();
        dg6 = new javax.swing.JLabel();
        tien6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tongcong = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        thue1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bangchu = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel20.setText("Chi so cu");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên KH:");

        jname.setText("jLabel2");

        jLabel3.setText("Mã công tơ:");

        jmeasid.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("HÓA ĐƠN TIỀN ĐIỆN");

        jLabel6.setText("Mã hóa đơn");

        jBillId.setText("jLabel7");

        jLabel8.setText("Địa chỉ:");

        jadd.setText("jLabel9");

        jLabel10.setText("SDT:");

        jphone.setText("jLabel11");

        jLabel2.setText("Sử dụng từ:");

        jLabel4.setText("jLabel4");

        jLabel7.setText("đến:");

        jLabel9.setText("jLabel9");

        jLabel11.setText("Mã KH:");

        jcusid.setText("jLabel12");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel15.setText("Chỉ số mới");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel16.setText("ĐN tiêu thụ");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg1.setText("1.678");
        dg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        csm.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        csm.setText("Chi so moi");
        csm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tt1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt1.setText("DN tieu thu1");
        tt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel23.setText("Đơn giá");
        jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel24.setText("Thành tiền");
        jLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tong.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tong.setText("DN tieu thu");
        tong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tt3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt3.setText("DN tieu thu 3");
        tt3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tt2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt2.setText("DN tieu thu2");
        tt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tt5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt5.setText("DN tieu thu5");
        tt5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tongtt.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tongtt.setText("DN tieu thu6");
        tongtt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tt4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt4.setText("DN tieu thu4");
        tt4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg2.setText("1.734");
        dg2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg3.setText("2.014");
        dg3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg4.setText("2.536");
        dg4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg5.setText("2.834");
        dg5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        lb.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tongthanhtien.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tongthanhtien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        csc1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        csc1.setText("Chi so cu");
        csc1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel12.setText("Tổng");

        tt6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tt6.setText("DN tieu thu6");
        tt6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        dg6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dg6.setText("2.927");
        dg6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        tien6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tien6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel13.setText("+Thuế: 10%");

        tongcong.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tongcong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel17.setText("Tổng số tiền phải thanh toán");

        thue1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        thue1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        jLabel18.setText("Bằng chữ:");

        bangchu.setText("jLabel19");

        jButton1.setText("Xác nhận và in hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setText("Chỉ số cũ");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(128, 128, 128), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jname))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jphone)
                                    .addComponent(jadd))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmeasid)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jcusid)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBillId)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(csc1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(csm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thue1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tongtt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tongthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tt4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dg4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tien4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bangchu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBillId))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jname)
                    .addComponent(jLabel3)
                    .addComponent(jmeasid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jadd)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jphone)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcusid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel19))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(csm)
                                        .addComponent(csc1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tien2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tt2)
                                        .addComponent(dg2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tien3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tt3)
                                        .addComponent(dg3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tien4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tt4)
                                        .addComponent(dg4)))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tien5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tt5)
                                        .addComponent(dg5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tt6)
                                            .addComponent(dg6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(tongtt)
                                                .addComponent(jLabel12))
                                            .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tien6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(tongthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thue1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(bangchu))
                .addGap(43, 43, 43)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Xác nhận thanh toán?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
            BillDAOImpl bdi = new BillDAOImpl(this.con);
            Bill bill = new Bill();
            bill.setId(this.billId);
            bill.setPaymentStatus(true);
            bdi.edit(bill);
        } else {
            // no option
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Payment(o).setVisible(true);
//            }
//        });
//    }
    public int[] tinhDN(int dn) {
        int res[] = {50, 50, 100, 100, 100, 10000};
        boolean isGreater = true;
        for (int i = 0; i < 6; i++) {
            if (isGreater) {
                System.out.println(dn);
                if (dn - res[i] > 0) {
                    dn = dn - res[i];
                } else {
                    res[i] = dn;
                    isGreater = false;
                }
            } else {

                int index = i;
                while (index <= 5) {
                    res[index] = 0;
                    index++;
                }

                break;
            }
        }
        return res;
    }

    String normalize(String s) {
        String ret = "";
        String[] so = s.split("\\.");
        //System.out.println(so[0]);
        int n = so[0].length() % 3 + 1;
        //System.out.println(n);
        //String[]res = new String[n+1];
        ret += so[1];

        int index = so[0].length() - 1;
        while (index >= 0 && n > 0) {
            String tmp = "";
            for (int i = 0; i < 3; i++) {
                if (index >= i) {
                    tmp = so[0].charAt(index - i) + tmp;
                } else {
                    break;
                }
            }
            ret = tmp + "." + ret;
            //System.out.println(tmp);
            index -= 3;
        }
        return ret;
    }

    String numToWord(char s, int ind) {
        switch (s) {
            case '1':
                if (ind == 0) {
                    return "một trăm";
                } else if (ind == 1) {
                    return "mười";
                } else {
                    return "một";
                }

            case '2':
                if (ind == 0) {
                    return "hai trăm";
                } else if (ind == 1) {
                    return "hai mươi";
                } else {
                    return "hai";
                }
            case '3':
                if (ind == 0) {
                    return "ba trăm";
                } else if (ind == 1) {
                    return "ba mươi";
                } else {
                    return "ba";
                }
            case '4':
                if (ind == 0) {
                    return "bốn trăm";
                } else if (ind == 1) {
                    return "bốn mươi";
                } else {
                    return "bốn";
                }
            case '5':
                if (ind == 0) {
                    return "năm trăm";
                } else if (ind == 1) {
                    return "năm mươi";
                } else {
                    return "lăm";
                }
            case '6':
                if (ind == 0) {
                    return "sáu trăm";
                } else if (ind == 1) {
                    return "sáu mươi";
                } else {
                    return "sáu";
                }
            case '7':
                if (ind == 0) {
                    return "bảy trăm";
                } else if (ind == 1) {
                    return "bảy mươi";
                } else {
                    return "bảy";
                }
            case '8':
                if (ind == 0) {
                    return "tám trăm";
                } else if (ind == 1) {
                    return "tám mươi";
                } else {
                    return "tám";
                }
            case '9':
                if (ind == 0) {
                    return "chín trăm";
                } else if (ind == 1) {
                    return "chín mươi";
                } else {
                    return "chín";
                }
            case '0':
                if (ind == 0) {
                    return "không trăm";
                } else if (ind == 1) {
                    return "linh";
                } else {
                    return "không";
                }
        }
        return null;
    }

    String toWord(String s[]) {
        int n = s.length;
        String res = "";

        if (n == 2) {
            if (s[0].length() == 1) {
                s[0] = "00" + s[0];

            } else if (s[0].length() == 2) {
                s[0] = "0" + s[0];

            }
            System.out.println(s[0].length());
            for (int i = 0; i < 3; i++) {

                String r = numToWord(s[0].charAt(i), i);
                System.out.println(r);

                res += r + " ";

            }
            res += "nghìn ";

            if (s[1].length() == 1) {
                s[1] = "00" + s[1];

            } else if (s[1].length() == 2) {
                s[1] = "0" + s[1];

            }
            for (int i = 0; i < 3; i++) {

                String r = numToWord(s[1].charAt(i), i);

                res += r + " ";

            }
            res += "đồng";

        } else if (n == 3) {
            if (s[0].length() == 1) {
                s[0] = "00" + s[0];

            } else if (s[0].length() == 2) {
                s[0] = "0" + s[0];

            }
            System.out.println(s[0].length());
            for (int i = 0; i < 3; i++) {

                String r = numToWord(s[0].charAt(i), i);
                System.out.println(r);

                res += r + " ";

            }
            res += "trieu ";

            if (s[1].length() == 1) {
                s[1] = "00" + s[1];

            } else if (s[1].length() == 2) {
                s[1] = "0" + s[1];

            }
            for (int i = 0; i < 3; i++) {

                String r = numToWord(s[1].charAt(i), i);

                res += r + " ";

            }
            res += "nghìn ";
            if (s[2].length() == 1) {
                s[2] = "00" + s[2];

            } else if (s[2].length() == 2) {
                s[2] = "0" + s[2];

            }
            for (int i = 0; i < 3; i++) {

                String r = numToWord(s[2].charAt(i), i);

                res += r + " ";

            }
            res += "đồng";
        }
        res = res.replaceFirst("không đồng", "đồng");
        res = res.replaceFirst("không nghìn", "nghìn");
        res = res.replaceFirst("không trăm linh", "");
        res = res.replaceFirst("linh không", "");
        res = res.replaceFirst("linh nghìn", "nghìn");
        return res;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangchu;
    private javax.swing.JLabel csc1;
    private javax.swing.JLabel csm;
    private javax.swing.JLabel dg1;
    private javax.swing.JLabel dg2;
    private javax.swing.JLabel dg3;
    private javax.swing.JLabel dg4;
    private javax.swing.JLabel dg5;
    private javax.swing.JLabel dg6;
    private javax.swing.JLabel jBillId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jadd;
    private javax.swing.JLabel jcusid;
    private javax.swing.JLabel jmeasid;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jphone;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel thue1;
    private javax.swing.JLabel tien1;
    private javax.swing.JLabel tien2;
    private javax.swing.JLabel tien3;
    private javax.swing.JLabel tien4;
    private javax.swing.JLabel tien5;
    private javax.swing.JLabel tien6;
    private javax.swing.JLabel tong;
    private javax.swing.JLabel tongcong;
    private javax.swing.JLabel tongthanhtien;
    private javax.swing.JLabel tongtt;
    private javax.swing.JLabel tt1;
    private javax.swing.JLabel tt2;
    private javax.swing.JLabel tt3;
    private javax.swing.JLabel tt4;
    private javax.swing.JLabel tt5;
    private javax.swing.JLabel tt6;
    // End of variables declaration//GEN-END:variables
}
